### ISSUE TITLE
Cannot build Draconic's Energy Core

### ISSUE THREAD

**Issue by TONY-All** [Nomi-CEu/Nomi-Labs#23]
Here's the report
```log
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]: java.lang.ClassCastException: com.cleanroommc.groovyscript.compat.mods.draconicevolution.helpers.BlockStateEnergyCoreStructure cannot be cast to com.nomiceu.nomilabs.integration.draconicevolution.BlockStateEnergyCoreStructure
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.nomiceu.nomilabs.integration.draconicevolution.DraconicHelpers.getStructureBlocks(DraconicHelpers.java:200)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.nomiceu.nomilabs.integration.draconicevolution.EnergyCoreBuilderLogic.buildWorklist(EnergyCoreBuilderLogic.java:45)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.nomiceu.nomilabs.integration.draconicevolution.EnergyCoreBuilderLogic.build(EnergyCoreBuilderLogic.java:28)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.lib.EnergyCoreBuilder.handler$zlf000$nomilabs$buildWorklist(EnergyCoreBuilder.java:551)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.lib.EnergyCoreBuilder.buildWorkList(EnergyCoreBuilder.java)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.lib.EnergyCoreBuilder.<init>(EnergyCoreBuilder.java:42)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyStorageCore.startOrStopBuilder(TileEnergyStorageCore.java:1218)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyStorageCore.handler$zll000$nomilabs$receivePacketFromClient(TileEnergyStorageCore.java:1142)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyStorageCore.receivePacketFromClient(TileEnergyStorageCore.java)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at com.brandon3055.brandonscore.network.ServerPacketHandler.handlePacket(ServerPacketHandler.java:28)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at net.minecraft.util.Util.func_181617_a(SourceFile:529)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
[10:35:25] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:34]:    at java.lang.Thread.run(Thread.java:750)
```

**Comment by IntegerLimit** [comment]
You have to set `enableDraconicEvolutionIntegration` in `groovyscript.cfg` to false for Nomi-Labs' to work.
